mail.host=sandbox.smtp.mailtrap.io
mail.port=2525
mail.username=081cf13f4d1211
mail.password=6d9f2fd0442469
app.mail=info.zyrotech@gmail.com
app.name=ZyroTech
app.url=http://localhost:8080/zyrotech
app.public.url=https://prestudious-amina-meekly.ngrok-free.dev/zyrotech
